CREATE TABLE "AIBudget" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "monthlyBudgetTHB" DECIMAL(12,2) NOT NULL DEFAULT 2000,
  "warningPercent" INTEGER NOT NULL DEFAULT 80,
  "enabled" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "AIBudget_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "AIBudget_userId_key" ON "AIBudget"("userId");
ALTER TABLE "AIBudget" ADD CONSTRAINT "AIBudget_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
